--어둠의 위조공장
local m=18453311
local cm=_G["c"..m]
function cm.initial_effect(c)
	local e1=MakeEff(c,"A")
	e1:SetCode(EVENT_FREE_CHAIN)
	e1:SetCategory(CATEGORY_TOHAND+CATEGORY_SEARCH)
	e1:SetCL(1,m+EFFECT_COUNT_CODE_OATH)
	WriteEff(e1,1,"O")
	c:RegisterEffect(e1)
	local e2=MakeEff(c,"F","F")
	e2:SetCode(EFFECT_UPDATE_ATTACK)
	e2:SetValue(300)
	e2:SetCondition(cm.con2)
	e2:SetTR("M",0)
	c:RegisterEffect(e2)
	local e3=MakeEff(c,"F","F")
	e3:SetCode(EFFECT_HATOTAURUS_TOKEN)
	e3:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e3:SetTR(1,0)
	e3:SetOperation(cm.op3)
	c:RegisterEffect(e3)
	local e4=e2:Clone()
	e4:SetCode(EFFECT_UPDATE_DEFENSE)
	c:RegisterEffect(e4)
end
function cm.ofil1(c)
	return c:IsCode(18453310) and c:IsAbleToHand()
end
function cm.op1(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	if c:IsRelateToEffect(e) then
		Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_ATOHAND)
		local g=Duel.SMCard(tp,cm.ofil1,tp,"D",0,0,1,nil)
			if #g>0 then
			Duel.SendtoHand(g,nil,REASON_EFFECT)
			Duel.ConfirmCards(1-tp,g)
		end
	end
end
function cm.con2(e)
	local tp=e:GetHandlerPlayer()
	return Duel.IEMCard(Card.IsType,tp,"M",0,1,nil,TYPE_TOKEN)
end
function cm.op3(c)
	local e1=MakeEff(c,"S")
	e1:SetCode(EFFECT_CANNOT_BE_FUSION_MATERIAL)
	e1:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
	e1:SetReset(RESET_EVENT+RESETS_STANDARD-RESET_TOFIELD)
	e1:SetValue(1)
	c:RegisterEffect(e1)
	local e2=e1:Clone()
	e2:SetCode(EFFECT_CANNOT_BE_SYNCHRO_MATERIAL)
	c:RegisterEffect(e2)
	local e3=e1:Clone()
	e3:SetCode(EFFECT_CANNOT_BE_LINK_MATERIAL)
	c:RegisterEffect(e3)
	local e4=e1:Clone()
	e4:SetCode(EFFECT_CANNOT_BE_ORDER_MATERIAL)
	c:RegisterEffect(e4)
	local e5=e1:Clone()
	e5:SetCode(EFFECT_CANNOT_BE_MODULE_MATERIAL)
	c:RegisterEffect(e5)
	local e6=e1:Clone()
	e6:SetCode(EFFECT_CANNOT_BE_SQUARE_MATERIAL)
	c:RegisterEffect(e6)
	local e7=e1:Clone()
	e7:SetCode(EFFECT_CANNOT_BE_BEYOND_MATERIAL)
	c:RegisterEffect(e7)
	local e8=e1:Clone()
	e8:SetCode(EFFECT_CANNOT_BE_DELIGHT_MATERIAL)
	c:RegisterEffect(e8)
	local e9=e1:Clone()
	e9:SetCode(EFFECT_UNRELEASABLE_SUM)
	c:RegisterEffect(e9)
	local ea=MakeEff(c,"S")
	ea:SetCode(EFFECT_CANNOT_DIRECT_ATTACK)
	ea:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
	ea:SetReset(RESET_EVENT+RESETS_STANDARD-RESET_TOFIELD+RESET_PHASE+PHASE_END,2)
	c:RegisterEffect(ea)
	local eb=MakeEff(c,"S","M")
	eb:SetCode(EFFECT_IMMUNE_EFFECT)
	eb:SetProperty(EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_SINGLE_RANGE)
	eb:SetCondition(cm.ocon3b)
	eb:SetValue(cm.oval3b)
	c:RegisterEffect(eb)
end
function cm.onfil3b(c,seq)
	local dis=math.abs(2-seq)
	local cdis=math.abs(2-c:GetSequence())
	return c:GetSequence()<5 and c:IsCode(99970687) and cdis<dis
end
function cm.ocon3b(e)
	local c=e:GetHandler()
	local tp=c:GetControler()
	return c:GetSequence()<5 and Duel.IEMCard(cm.onfil3b,tp,"M",0,1,nil,c:GetSequence())
end
function cm.oval3b(e,te)
	return te:GetOwnerPlayer()~=e:GetHandlerPlayer()
end