--아카스크립트리피스
function c27182818.initial_effect(c)
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetProperty(EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e1:SetCode(EFFECT_SPSUMMON_CONDITION)
	c:RegisterEffect(e1)
	local e2=Effect.CreateEffect(c)
	e2:SetType(EFFECT_TYPE_SINGLE)
	e2:SetCode(EFFECT_TRIBUTE_LIMIT)
	e2:SetValue(c27182818.val2)
	c:RegisterEffect(e2)
	local e3=Effect.CreateEffect(c)
	e3:SetType(EFFECT_TYPE_SINGLE)
	e3:SetProperty(EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e3:SetCode(EFFECT_LIMIT_SUMMON_PROC)
	e3:SetCondition(c27182818.con3)
	e3:SetOperation(c27182818.op3)
	e3:SetValue(SUMMON_TYPE_ADVANCE)
	c:RegisterEffect(e3)
	local e4=e3:Clone()
	e4:SetCode(EFFECT_LIMIT_SET_PROC)
	c:RegisterEffect(e4)
	local e5=Effect.CreateEffect(c)
	e5:SetType(EFFECT_TYPE_FIELD)
	e5:SetCode(EFFECT_UPDATE_ATTACK)
	e5:SetRange(LOCATION_MZONE)
	e5:SetTargetRange(0,LOCATION_MZONE)
	e5:SetValue(-800)
	e5:SetProperty(EFFECT_FLAG_IGNORE_IMMUNE)
	c:RegisterEffect(e5)
	local e6=e5:Clone()
	e6:SetCode(EFFECT_UPDATE_DEFENSE)
	c:RegisterEffect(e6)
	local e7=Effect.CreateEffect(c)
	e7:SetType(EFFECT_TYPE_SINGLE)
	e7:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e7:SetRange(LOCATION_MZONE)
	e7:SetCode(EFFECT_IMMUNE_EFFECT)
	e7:SetLabel(4)
	e7:SetCondition(c27182818.con7)
	e7:SetValue(c27182818.val7)
	c:RegisterEffect(e7)
	local e8=Effect.CreateEffect(c)
	e8:SetType(EFFECT_TYPE_IGNITION)
	e8:SetCategory(CATEGORY_TOGRAVE)
	e8:SetRange(LOCATION_MZONE)
	e8:SetProperty(EFFECT_FLAG_CARD_TARGET+EFFECT_FLAG_IGNORE_IMMUNE)
	e8:SetCountLimit(1)
	e8:SetLabel(3)
	e8:SetCondition(c27182818.con7)
	e8:SetTarget(c27182818.tg8)
	e8:SetOperation(c27182818.op8)
	c:RegisterEffect(e8)
	local e9=Effect.CreateEffect(c)
	e9:SetType(EFFECT_TYPE_SINGLE)
	e9:SetCode(EFFECT_INDESTRUCTABLE_BATTLE)
	e9:SetValue(1)
	e9:SetLabel(2)
	e9:SetCondition(c27182818.con7)
	c:RegisterEffect(e9)
	local ea=Effect.CreateEffect(c)
	ea:SetType(EFFECT_TYPE_SINGLE)
	ea:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	ea:SetCode(EFFECT_UNRELEASABLE_SUM)
	ea:SetRange(LOCATION_MZONE)
	ea:SetValue(1)
	ea:SetLabel(2)
	ea:SetCondition(c27182818.con7)
	c:RegisterEffect(ea)
	local eb=ea:Clone()
	eb:SetCode(EFFECT_UNRELEASABLE_NONSUM)
	c:RegisterEffect(eb)
	local ec=Effect.CreateEffect(c)
	ec:SetType(EFFECT_TYPE_FIELD)
	ec:SetRange(LOCATION_MZONE)
	ec:SetCode(EFFECT_CANNOT_SUMMON)
	ec:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	ec:SetTargetRange(0,1)
	ec:SetLabel(1)
	ec:SetCondition(c27182818.con7)
	c:RegisterEffect(ec)
	local ed=ec:Clone()
	ed:SetCode(EFFECT_CANNOT_SPECIAL_SUMMON)
	c:RegisterEffect(ed)
	local ee=Effect.CreateEffect(c)
	ee:SetType(EFFECT_TYPE_FIELD)
	ee:SetRange(LOCATION_MZONE)
	ee:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	ee:SetCode(EFFECT_CANNOT_ACTIVATE)
	ee:SetTargetRange(0,1)
	ee:SetValue(c27182818.vale)
	ee:SetLabel(1)
	ee:SetCondition(c27182818.con7)
	c:RegisterEffect(ee)
end
function c27182818.val2(e,c)
	return not c:IsSetCard(0x2c2)
end
function c27182818.con3(e,c)
	if c==nil then
		return true
	end
	return Duel.GetLocationCount(c:GetControler(),LOCATION_MZONE)>-3 and Duel.GetTributeCount(c)>=3
end
function c27182818.op3(e,tp,eg,ep,ev,re,r,rp,c)
	local g=Duel.SelectTribute(tp,c,3,3)
	c:SetMaterial(g)
	Duel.Release(g,REASON_SUMMON+REASON_MATERIAL)
end
function c27182818.con7(e,tp,eg,ep,ev,re,r,rp)
	return Duel.GetFieldGroupCount(e:GetHandlerPlayer(),LOCATION_ONFIELD+LOCATION_HAND,0)<=e:GetLabel()
end
function c27182818.val7(e,te)
	if te:IsActiveType(TYPE_SPELL+TYPE_TRAP) then
		return true
	end
	if te:IsActiveType(TYPE_MONSTER) and te:IsHasType(0x7e0) then
		local lv=e:GetHandler():GetLevel()
		local ec=te:GetHandler()
		if ec:IsType(TYPE_XYZ) then
			return ec:GetOriginalRank()<lv
		else
			return ec:GetOriginalLevel()<lv
		end
	end
	return false
end
function c27182818.tg8(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then
		return Duel.IsExistingTarget(nil,tp,0,LOCATION_ONFIELD,1,nil)
	end
	local g=Duel.SelectTarget(tp,nil,tp,0,LOCATION_ONFIELD,1,1,nil)
	Duel.SetOperationInfo(0,CATEGORY_TOGRAVE,g,1,0,0)
end
function c27182818.op8(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local tc=Duel.GetFirstTarget()
	if tc:IsRelateToEffect(e) then
		local e1=Effect.CreateEffect(c)
		e1:SetType(EFFECT_TYPE_SINGLE)
		e1:SetCode(EFFECT_DISABLE)
		e1:SetReset(RESET_EVENT+0x1fe000)
		tc:RegisterEffect(e1)
		local e2=Effect.CreateEffect(c)
		e2:SetType(EFFECT_TYPE_SINGLE)
		e2:SetCode(EFFECT_DISABLE_EFFECT)
		e2:SetReset(RESET_EVENT+0x1fe000)
		tc:RegisterEffect(e2)
		Duel.SendtoGrave(tc,REASON_RULE)
	end
end
function c27182818.vale(e,re,tp)
	return not re:GetHandler():IsImmuneToEffect(e)
end