function c52641008.initial_effect(c)
	    aux.AddFusionProcMixRep(c,true,true,aux.FilterBoolFunction(Card.IsFusionSetCard,0x5f1),2,99)
		c:EnableReviveLimit()
	local e1=Effect.CreateEffect(c)
    e1:SetType(EFFECT_TYPE_SINGLE)
    e1:SetCode(EFFECT_MATERIAL_CHECK)
    e1:SetValue(c52641008.matcheck)
    c:RegisterEffect(e1)
	--indes
	local e2=Effect.CreateEffect(c)
    e2:SetType(EFFECT_TYPE_FIELD)
    e2:SetCode(EFFECT_INDESTRUCTABLE_EFFECT)
    e2:SetRange(LOCATION_MZONE)
    e2:SetTargetRange(LOCATION_MZONE,0)
    e2:SetCondition(c52641008.indcon)
    e2:SetTarget(aux.TargetBoolFunction(Card.IsType,0x5f1))
    e2:SetValue(c52641008.indval)
    c:RegisterEffect(e2)
    --cannot be target
    local e3=Effect.CreateEffect(c)
    e3:SetType(EFFECT_TYPE_FIELD)
    e3:SetCode(EFFECT_CANNOT_BE_EFFECT_TARGET)
    e3:SetProperty(EFFECT_FLAG_IGNORE_IMMUNE)
    e3:SetRange(LOCATION_MZONE)
    e3:SetTargetRange(LOCATION_MZONE,0)
    e3:SetCondition(c52641008.indcon)
    e3:SetTarget(aux.TargetBoolFunction(Card.IsType,0x5f1))
    e3:SetValue(aux.tgoval)
    c:RegisterEffect(e3)
end
c52641008.material_setcode=0x5f1
function c52641008.matcheck(e,c)
    local ct=c:GetMaterialCount()
    local e1=Effect.CreateEffect(c)
    e1:SetType(EFFECT_TYPE_SINGLE)
    e1:SetCode(EFFECT_UPDATE_ATTACK)
    e1:SetValue(ct*500)
    e1:SetReset(RESET_EVENT+0xff0000)
    c:RegisterEffect(e1)
end
function c52641008.indfilter(c)
    return c:IsFaceup() and c:IsSetCard(0x5f1)
end
function c52641008.indcon(e)
    return Duel.IsExistingMatchingCard(c52641008.indfilter,e:GetHandlerPlayer(),LOCATION_MZONE,LOCATION_MZONE,1,e:GetHandler())
end
function c52641008.indval(e,re,rp)
    return rp~=e:GetHandlerPlayer()
end