io.open("expansions/desc.lua","w",-1,"ansi")
local file=io.open("expansions/desc.lua","a")
file:write("data_desc={}\n")
file:write("function data_manager_desc(desc,chk)\n")
file:write("   if data_desc[desc] then\n")
file:write("      return data_desc[desc]\n")
file:write("   end\n")
file:write("   return false\n")
file:write("end\n")
file:close()